kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kertical-metrics-auth-rolebinding
  labels:
    {{- include "kertical-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kertical-metrics-auth-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controller.manager.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
