kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kertical-metrics-reader-role
  labels:
    {{- include "kertical-manager.labels" . | nindent 4 }}
rules:
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
