kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kertical-networking-externalproxy-admin-role
  labels:
    {{- include "kertical-manager.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - networking.kertical.com
    resources:
      - externalproxies
    verbs:
      - '*'
  - apiGroups:
      - networking.kertical.com
    resources:
      - externalproxies/status
    verbs:
      - get
