kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: forwarding
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: kertical
    app.kubernetes.io/component: forwarding
    app.kubernetes.io/part-of: kertical
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kertical
      app.kubernetes.io/component: forwarding
      app.kubernetes.io/part-of: kertical
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kertical
        app.kubernetes.io/component: forwarding
        app.kubernetes.io/part-of: kertical
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: sysctl
          image: busybox
          command:
            - /bin/sh
            - -c
            - sysctl -w net.ipv4.ip_forward=1
          securityContext:
            privileged: true
      containers:
        - name: forwarding
          image: forwarding:latest
          args:
            - --health-probe-bind-address=:8081
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - NET_ADMIN
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
      serviceAccountName: forwarding
      terminationGracePeriodSeconds: 10
