apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- webhook-manager.yaml
- webhook-rbac.yaml

images:
- name: webhook-manager
  newName: wjiec/kertical-webhook
  newTag: v0.1.1
