kind: ServiceAccount
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: kertical
    app.kubernetes.io/managed-by: kustomize
  name: webhook-manager
  namespace: system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: kertical
    app.kubernetes.io/managed-by: kustomize
  name: webhook-manager-role
  namespace: system
rules:
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
      - services
      - pods
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: kertical
    app.kubernetes.io/managed-by: kustomize
  name: webhook-manager-admission-rolebinding
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webhook-manager-role
subjects:
  - kind: ServiceAccount
    name: webhook-manager
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: kertical
    app.kubernetes.io/managed-by: kustomize
  name: webhook-manager-editor-rolebinding
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: editor-role
subjects:
  - kind: ServiceAccount
    name: webhook-manager
