apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kertical
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: kertical
  name: webhook-service
  namespace: system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: controller-manager
    app.kubernetes.io/component: webhook
