kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: kertical
    app.kubernetes.io/managed-by: kustomize
  name: editor-role
rules:
  - apiGroups:
      - networking.kertical.com
    resources:
      - externalproxies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: kertical
    app.kubernetes.io/managed-by: kustomize
  name: viewer-role
rules:
  - apiGroups:
      - networking.kertical.com
    resources:
      - externalproxies
    verbs:
      - get
      - list
      - watch
