kind: Deployment
apiVersion: apps/v1
metadata:
  name: kuard
  labels:
    app.kubernetes.io/name: kertical
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: kertical
      app.kubernetes.io/component: kuard
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kertical
        app.kubernetes.io/component: kuard
        app.kubernetes.io/managed-by: kustomize
    spec:
      containers:
        - name: kuard
          image: gcr.io/kuar-demo/kuard-amd64:blue
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: kuard
  labels:
    app.kubernetes.io/name: kertical
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/name: kertical
    app.kubernetes.io/component: kuard
---
kind: Service
apiVersion: v1
metadata:
  name: kuard-headless
  labels:
    app.kubernetes.io/name: kertical
    app.kubernetes.io/managed-by: kustomize
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: kertical
    app.kubernetes.io/component: kuard
---
kind: PortForwarding
apiVersion: networking.kertical.com/v1alpha1
metadata:
  labels:
    app.kubernetes.io/name: kertical
    app.kubernetes.io/managed-by: kustomize
  name: portforwarding-regular
spec:
  serviceRef:
    name: kuard
  ports:
    - target: http
      hostPort: 58080
---
kind: PortForwarding
apiVersion: networking.kertical.com/v1alpha1
metadata:
  labels:
    app.kubernetes.io/name: kertical
    app.kubernetes.io/managed-by: kustomize
  name: portforwarding-headless
spec:
  serviceRef:
    name: kuard-headless
  ports:
    - target: 8080
      hostPort: 58081
