apiVersion: networking.kertical.com/v1alpha1
kind: PortForwarding
metadata:
  labels:
    app.kubernetes.io/name: kertical
    app.kubernetes.io/managed-by: kustomize
  name: portforwarding-sample
spec:
  # TODO(user): Add fields here
