kind: Service
apiVersion: v1
metadata:
  name: {{ include "kertical-manager.webhook.metrics-service.name" . }}
  labels:
    {{- include "kertical-manager.webhook.labels" . | nindent 4 }}
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    {{- include "kertical-manager.webhook.selectorLabels" . | nindent 4 }}
