kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.controller.webhook.serviceAccount.name }}
  labels:
    {{- include "kertical-manager.labels" . | nindent 4 }}
    {{- include "kertical-manager.webhook.componentLabels" . | nindent 4 }}
  {{- with .Values.controller.webhook.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
