kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-forwarding-rolebinding
  labels:
    {{- include "kertical-manager.forwarding.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-forwarding-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controller.forwarding.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
