kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-forwarding-role
  labels:
    {{- include "kertical-manager.forwarding.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.kertical.com
    resources:
      - portforwardings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - networking.kertical.com
    resources:
      - portforwardings/finalizers
    verbs:
      - update
  - apiGroups:
      - networking.kertical.com
    resources:
      - portforwardings/status
    verbs:
      - get
      - patch
      - update
