kind: ServiceAccount
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: kertical
    app.kubernetes.io/managed-by: kustomize
  name: gencert-init
  namespace: system
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: kertical
    app.kubernetes.io/managed-by: kustomize
  name: gencert-init-role
  namespace: system
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - update
      - create
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: kertical
    app.kubernetes.io/managed-by: kustomize
  name: gencert-init-rolebinding
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gencert-init-role
subjects:
  - kind: ServiceAccount
    name: gencert-init
