kind: Job
apiVersion: batch/v1
metadata:
  name: gencert
  namespace: system
  labels:
    app.kubernetes.io/name: kertical
    app.kubernetes.io/managed-by: kustomize
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gencert
        app.kubernetes.io/component: gencert
        app.kubernetes.io/part-of: kertical
        app.kubernetes.io/managed-by: kustomize
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      restartPolicy: Never
      containers:
        - name: gencert
          image: gencert:latest
          args: []
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
      # serviceAccountName will be substituted by kustomize
      serviceAccountName: gencert-init
