kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kertical-manager.gencert.name" . }}-rolebinding
  labels:
    {{- include "kertical-manager.labels" . | nindent 4 }}
  annotations:
    {{- include "kertical-manager.gencert.annotations" . | nindent 4 }}
    helm.sh/hook-weight: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kertical-manager.gencert.name" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.gencert.serviceAccount.name }}
