kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kertical-manager.gencert.name" . }}-role
  labels:
    {{- include "kertical-manager.labels" . | nindent 4 }}
  annotations:
    {{- include "kertical-manager.gencert.annotations" . | nindent 4 }}
    helm.sh/hook-weight: "0"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - update
      - create
