kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.gencert.serviceAccount.name }}
  labels:
    {{- include "kertical-manager.labels" . | nindent 4 }}
  annotations:
    {{- include "kertical-manager.gencert.annotations" . | nindent 4 }}
    helm.sh/hook-weight: "0"
