kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-webhook-admission-rolebinding
  labels:
    {{- include "kertical-manager.webhook.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-webhook-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controller.webhook.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-webhook-editor-rolebinding
  labels:
    {{- include "kertical-manager.webhook.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kertical-editor-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controller.webhook.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
